
export default {
  LOAD_TUTORIALS_SUCCESS     : 'LOAD_TUTORIALS_SUCCESS',
  LOAD_TUTORIAL_SUCCESS      : 'LOAD_TUTORIAL_SUCCESS',
  UPDATE_TUTORIAL_SUCCESS    : 'UPDATE_TUTORIAL_SUCCESS',
  LOAD_TRANSLATIONS_SUCCESS : 'LOAD_TRANSLATIONS_SUCCESS',
  LOAD_TRANSLATION_SUCCESS  : 'LOAD_TRANSLATION_SUCCESS',
  UPDATE_TRANSLATION_SUCCESS: 'UPDATE_TRANSLATION_SUCCESS'
};
